import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";
import JSZip from "jszip";

export const runtime = "nodejs";
export const maxDuration = 300; // 5 min timeout for Vercel serverless

interface ExportRequest {
  totalPages: number;
  data: Array<{
    pageNumber: number;
    title: string;
    records: Array<Record<string, unknown>>;
  }>;
}

/**
 * Generate a single PDF from page data
 * Returns a Buffer containing the PDF
 */
function generatePDF(pageData: {
  pageNumber: number;
  title: string;
  records: Array<Record<string, unknown>>;
}): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(18).font("Helvetica-Bold").text(pageData.title, { align: "center" });
    doc.fontSize(12).fillColor("#666").text(`Page ${pageData.pageNumber}`, { align: "center" });
    doc.moveDown(1);

    // Records as table-like format
    doc.fontSize(10).fillColor("#000");
    pageData.records.forEach((record, idx) => {
      doc.text(`Record ${idx + 1}:`, { underline: true });
      Object.entries(record).forEach(([key, value]) => {
        doc.fontSize(9).text(`  ${key}: ${String(value).slice(0, 80)}`);
      });
      doc.moveDown(0.5);
    });

    doc.addPage().fontSize(9).fillColor("#999").text("Generated by Tableau Bulk PDF Export", { align: "center" });
    doc.end();
  });
}

/**
 * POST /api/export-pdfs
 * Expects: { totalPages: N, data: [ { pageNumber, title, records } ] }
 * Returns: ZIP file containing page_1.pdf, page_2.pdf, etc.
 */
export async function POST(req: NextRequest) {
  try {
    const body: ExportRequest = await req.json();
    const { totalPages, data } = body;

    if (!totalPages || !Array.isArray(data) || data.length === 0) {
      return NextResponse.json(
        { error: "Missing or invalid totalPages or data" },
        { status: 400 }
      );
    }

    // Generate PDFs for each page in parallel
    const pdfBuffers = await Promise.all(
      data.map((pageData) => generatePDF(pageData))
    );

    // Create ZIP
    const zip = new JSZip();
    pdfBuffers.forEach((buffer, idx) => {
      const pageNum = data[idx].pageNumber;
      zip.file(`page_${pageNum}.pdf`, buffer);
    });

    const zipBuffer = await zip.generateAsync({ type: "arraybuffer" });

    // Return as downloadable ZIP
    return new Response(zipBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="tableau-export-${Date.now()}.zip"`
      }
    });
  } catch (err: any) {
    console.error("Export error:", err);
    return NextResponse.json(
      { error: err.message || "Export failed" },
      { status: 500 }
    );
  }
}
